### ISSUE TITLE
Using power sensor makes climate lose AC state

### ISSUE THREAD

**Issue by maxcanna** [smartHomeHub/SmartIR#445] opened 2020-08-10 15:10 UTC
**Home Assistant version**

0.113.3

**SmartIR version**

1.12.0

**SmartIR configuration**

```yaml

  - platform: smartir
    name: Soggiorno
    unique_id: soggiorno_climate
    device_code: 1180
    controller_data: 192.168.0.112
    power_sensor: binary_sensor.soggiorno_climate_contact
    temperature_sensor: sensor.soggiorno_temperature
    humidity_sensor: sensor.soggiorno_humidity

```

**Describe the bug**

I'm using `power_sensor` parameter to report AC state to SmartIR.
Problem is when I turn it on (using SmartIR itself). 
Sensor defined as `power_sensor` goes from `off` to `on` but the `climate` entity in HA makes these transitions:
- `off` -> `cool`
- `cool` -> `off`
- `off` -> `on`

This is wrong and, making thing worse, it loses the status so I don't see the mode and the temp in HA but just `on`.

**Debug log**

```text

NA

```

**Additional context**

I checked the value of `binary_sensor.soggiorno_climate_contact` and is working as expected without any bounce between values. It correctly reports the state of the AC.

**Comment by Hagakurje** [comment] 2020-08-17 16:33
Same problem.

**Comment by maxcanna** [comment] 2020-08-17 16:36
@Hagakurje another thing I noticed is that if I turn off the climate using HA but it doesn't work for whatever reason (just put a piece of paper in front of the IR) it still reports `off` as state regardless of the `power_sensor` state. Could you try that too? Thx

**Comment by Hagakurje** [comment] 2020-08-17 16:49
@maxcanna yes, the same situation.
1. AC working, state 'cool'
2. Restart HA, AC still working, but state 'on'. Why 'on' instead of 'cool'? Atter off and on state changed to 'cool'
3. cover IR, turn off AC (set hvac mode 'off') - AC working, contact sensor 'on', AC state 'off'

**Comment by Hagakurje** [comment] 2020-08-19 05:27
@maxcanna, you can try my fork https://github.com/Hagakurje/SmartIR Install from HACS, or manual, like original SmartIR. Please read https://github.com/Hagakurje/SmartIR/blob/master/docs/CLIMATE.md first, and add new params to your config after install.

**Comment by maxcanna** [comment] 2020-08-19 12:08
@Hagakurje I stole your new codes file 😅 I saw your code but I didn't understand how you intend to fix the problem

**Comment by Hagakurje** [comment] 2020-08-19 12:18
@maxcanna what exactly you can't understand? On power sensor change (_async_power_sensor_changed) and after command send (send_command) I check thermostat state and power sensor state (check_state). If states are not equal, I try to send command again, if does not help, I restore previous thermostat state. Have you read https://github.com/Hagakurje/SmartIR/blob/master/docs/CLIMATE.md#configuration-variables ?

**Comment by maxcanna** [comment] 2020-08-19 12:33
Yes, I saw the README and the source code. I'm just not sure that's the right way to solve the problem. SmartIR should ignore (or handle better) the `power_sensor` state change when you turn the AC on. Instead you send the command again

**Comment by smartHomeHub** [comment] 2020-08-19 12:48
> I'm just not sure that's the right way to solve the problem. SmartIR should ignore (or handle better) the `power_sensor` state change when you turn the AC on. Instead you send the command again

Agree. I'm on summer vacation right now. Most likely this pr will not merge. I will see the whole issue when I return to the beginning of next month

**Comment by Hagakurje** [comment] 2020-08-19 13:08
Why I need to prefer thermostat state to remote control:
- short-term power loss. After it HA works, because of UPS. But AC is off. So I want  turn it on, with last command, of course.
- when window is open, AC must be off. I exactly don't want turn AC on, when window is open. In any reason.

If my code is not good - ok, no problem. But I need some parameter/mode/switch/any else for totally prefer thermostat state to remote control.

**Comment by maxcanna** [comment] 2020-08-19 13:23
> short-term power loss. After it HA works, because of UPS. But AC is off. So I want turn it on, with last command, of course.

If SmartIR handles `power_sensor` you'll see the AC off in HA too so that's not a problem 🙂 

> when window is open, AC must be off. I exactly don't want turn AC on, when window is open. In any reason.

I don't understand this

**Comment by Hagakurje** [comment] 2020-08-19 13:44
> If SmartIR handles `power_sensor` you'll see the AC off in HA too so that's not a problem 🙂

It is a problem. I don't want 'off' state in HA. I don't want to open HA and look on state.  A want my AC on. It's easy, isn't it? 'Smart' home must solve simple problems. 

> I don't understand this

Simple automation - turn off AC when window is open. So, if any person turn AC on using remote, I want to turn it off. And the easiest way - SmartIR turn it off back.

In my home I don't use remote at all. HA turn AC on and off, change fan and temperature. So, if some problems appears (HA state not equal to power sensor state) for any reason, I need something to set my AC (not HA!) to correct state.

**Comment by maxcanna** [comment] 2020-08-19 13:49
You've to understand that automation should be delegated to HA, not the component. What's good for you isn't ok for others. You can't embed automations and behaviors into a component.

If you want your AC on, and it isn't because of the power loss, you should make HA turn it on again seeing it isn't. Not the component itself. 🙂  But we're OT here

**Comment by maxcanna** [comment] 2020-09-06 22:10
Hi @smartHomeHub did you get a chance to look at this?

**Comment by maxcanna** [comment] 2020-09-20 18:14
@smartHomeHub sorry to insist, could you please look into this? Losing the current state is detrimental to Google Home integration since once the climate is in undefined status it refuses to control it. This means that you cannot control it nor turn it off

**Comment by maxcanna** [comment] 2020-10-06 19:57
Don't want to push you @smartHomeHub but I didn't have any feedback. Could you please let me know?

**Comment by rexer78** [comment] 2020-10-19 11:32
Same problem to me HA 0.116.4

**Comment by trankillity** [comment] 2020-11-02 03:49
Bumping this again @smartHomeHub, problem as @maxcanna describes it is exactly what I'm seeing. Either need to maintain the state set by SmartIR when combined with a `power_sensor`, or expose the fake "on" state to the Climate entity so that Google can control it.

**Comment by maxcanna** [comment] 2020-11-23 17:18
@smartHomeHub could you please take a look at this? 🙏🏻

**Comment by maxcanna** [comment] 2021-01-02 18:32
@smartHomeHub could you please answer us on this? 🙏🏻

**Comment by vassilis-panos** [comment] 2021-01-06 10:09
Although I do not agree with the approach because things can go out of sync, in the latest version you can add `power_sensor_restore_state: true` to the configuration file.
```
climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac1
    device_code: 1000
    controller_data: remote.office_remote
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.climate_power
    power_sensor_restore_state: true
```

This parameter will remain undocumented.

**Comment by maxcanna** [comment] 2021-01-06 10:13
Fixed by 38a1cbfc30796eba0573cfa247f4968516d23349

Thank you @vassilis-panos

**Comment by maxcanna** [comment] 2021-01-06 10:16
Just saw your message. Why are you saying this is wrong? What should I do? I just configured a `power_sensor` to have feedback of the AC status. Was it intended just to detect power on by remote?

**Comment by a005** [comment] 2021-01-06 15:28
Hi, I commited in my repo attempt to fix 'out of sync power_sensor and hvac_state' caused by IR commands lost or something.
The main idea is to update the hvac status only after the power_sensor status update.


[commit here](https://github.com/a005/SmartIR/commit/f0bcf51cef22240a84bdda4f2a29787dbb3d6c2d)

If it meet to requirements, I'll try to make a pull request (sorry, i'm not pro python programmer).

**Comment by smartHomeHub** [comment] 2021-01-06 15:33
Please hide your remote controls in a drawer 😂

**Comment by maxcanna** [comment] 2021-01-06 15:35
> Please hide your remote controls in a drawer 😂

This is exactly what I did 😅  But this led to the problem I reported.

If I don't use remotes and I can't use an external sensor to report state back into HA, what's the purpose of that config field?

**Comment by smartHomeHub** [comment] 2021-01-06 15:39
What state? If the device is actually turned on?

**Comment by maxcanna** [comment] 2021-01-06 15:42
> What state? If the device is actually turned on?

Yes, exactly. Having a dumb climate I can't control it (that's the main goal of SmartIR) and have its state in HA.
I need to know if it's on and, more important, if it's off.

A friend of mine spent a lot of money leaving his climate on for a month while he was not home.

**Comment by a005** [comment] 2021-01-06 15:43
> What state? If the device is actually turned on?

Any state that changes the state of the power sensor

**Comment by trankillity** [comment] 2021-01-07 06:54
> Please hide your remote controls in a drawer 😂

@smartHomeHub, @vassilis-panos - I think that you're missing the point of this issue because @Hagakurje derailed it with a different issue. Your proposed fix is for @Hagakurje's issue, NOT the core problem of this issue.

The problem is that the SmartIR component is changing the state of the AC to 'on' AFTER the state is already set by SmartIR because the `power_sensor` is triggering on after initial IR is sent. In my instance, this is caused because I use a contact sensor as my `power_sensor`.

So the flow goes:

* Set state to `Heat/Cool`
* IR sends command to AC
* AC vane opens, triggering `power_sensor`
* SmartIR receives updated power state
* SmartIR sets climate state to `on` instead of keeping the state that is set by SmartIR

This was actually addressed in @maxcanna's patch, [here](https://github.com/smartHomeHub/SmartIR/pull/533) - however I don't believe this has actually been merged in this update, as it appears to just be restoring the previous state - not ignoring state change if the state is already set.

As you mentioned, this can result in out-of-sync climate entities, whereas @maxcanna's patch purely addresses the core of this issue.

**Comment by vassilis-panos** [comment] 2021-01-07 07:23
> The problem is that the SmartIR component is changing the state of the AC to 'on' AFTER the state is already set by SmartIR because the `power_sensor` is triggering on after initial IR is sent. In my instance, this is caused because I use a contact sensor as my `power_sensor`.

This should not be happening. SmartΙR is not changing the state when a power sensor goes form off to on and the climate component is in a different state from off.

The only reason I can think of it is that your contact sensors goes on -> off -> on instantly after your air conditioner is switched on (Due to flap calibration?). Can you check it?

**Comment by maxcanna** [comment] 2021-01-07 08:20
> The only reason I can think of it is that your contact sensors goes on -> off -> on instantly after your air conditioner is switched on (Due to flap calibration?). Can you check it?

I already checked it and reported in the OP as additional context. Sensor is absolutely fine.
That's why I'm asking this to be the right, and default, behavior. I'm not sure why you won't document it and consider it bad practice.

@trankillity As I already said, I used the newly added param and it solves the issue.

**Comment by vassilis-panos** [comment] 2021-01-07 08:27
The new parameter hides the problem... I have to reproduce it. What is your contact sensor?

**Comment by maxcanna** [comment] 2021-01-07 08:56
> The new parameter hides the problem... I have to reproduce it. What is your contact sensor?

Aqara zigbee door and window sensor integrated in HA using z2m

**Comment by trankillity** [comment] 2021-01-07 10:49
> > The problem is that the SmartIR component is changing the state of the AC to 'on' AFTER the state is already set by SmartIR because the `power_sensor` is triggering on after initial IR is sent. In my instance, this is caused because I use a contact sensor as my `power_sensor`.
> 
> This should not be happening. SmartΙR is not changing the state when a power sensor goes form off to on and the climate component is in a different state from off.
> 
> The only reason I can think of it is that your contact sensors goes on -> off -> on instantly after your air conditioner is switched on (Due to flap calibration?). Can you check it?

![Sensor](https://user-images.githubusercontent.com/53357041/103884064-c70da000-5129-11eb-86cc-bf94e59c36ac.jpg)

Here you can see that the sensor only triggers once to on, then once again to off. Using Wyze sensors with WyzeSense2MQTT.

**Comment by vassilis-panos** [comment] 2021-01-07 11:03
I’m sure is something with mqtt and attributes. I had a similar issue with automations. Mqtt triggers them twice. It first sends the attributes and then the state.
In this case `if new_state.state == old_state.state: return` is the solution

**Comment by maxcanna** [comment] 2021-01-07 11:43
@vassilis-panos it shouldn't matter how the sensor is working underneath since SmartIR works at "HA level" isn't it?

**Comment by vassilis-panos** [comment] 2021-01-07 11:58
I just tried it with a mqtt sensor. _async_power_sensor_changed fires twice.

First fire -> state: off, attributes {xxx}
Second fire -> state: on, atributes: null

**Closed** 2021-01-07 12:11 UTC

**Comment by a005** [comment] 2021-01-07 12:44
https://github.com/smartHomeHub/SmartIR/issues/445#issuecomment-674984925

> @Hagakurje another thing I noticed is that if I turn off the climate using HA but it doesn't work for whatever reason (just put a piece of paper in front of the IR) it still reports `off` as state regardless of the `power_sensor` state. Could you try that too? Thx

This issue not fixed

**Comment by smartHomeHub** [comment] 2021-01-07 12:46
This is a different issue

**Comment by maxcanna** [comment] 2021-01-07 14:15
@smartHomeHub I'll try this new version (w/o the new param) and let you know

**Comment by maxcanna** [comment] 2021-01-07 14:23
ok, test done, the second fix is enough

**Comment by trankillity** [comment] 2021-01-08 00:02
Also tested new version without the `power_sensor_restore_state: true` and it's working fine. Thanks for the update!
